### ISSUE TITLE
Data capture into a csv file

### ISSUE THREAD

**Issue by Jeffreylarbiakor** [Jeffreylarbiakor/Momento_TimeTracker#1]
Hello team,
This is a good first version, @ivyodametey. I think there is a problem with the function to write Nana's file to a csv file. Can you check on this, @IMQUARTEY?

**Comment by IMQUARTEY** [comment]
@Jeffreylarbiakor,I agree with you. 
I'm working on it now

**Comment by Jeffreylarbiakor** [comment]
I have seen your update @IMQUARTEY. I will review this in your First_edit branch

**Comment by ivyodametey** [comment]
Great @IMQUARTEY 
I think importing the writer was missing from the codes.
