### ISSUE TITLE
date output

### ISSUE THREAD

**Issue by ivyodametey** [Jeffreylarbiakor/Momento_TimeTracker#2]
Hi guys!
Thanks for for solving the issue @IMQUARTEY , however @Jeffreylarbiakor @IMQUARTEY,  the time for both start and finish appears together with 1900-01-01. I think we need to work on it. What do you think?

**Comment by Jeffreylarbiakor** [comment]
Yes, @ivyodametey . I agree with you. I also discovered another issue with the date format. I will work on this now.

**Comment by ivyodametey** [comment]
Alright I'm also checking it.
