### ISSUE TITLE
Automated Time and Date Capture

### ISSUE THREAD

**Issue by Jeffreylarbiakor** [Jeffreylarbiakor/Momento_TimeTracker#5]
Hello team,
How can the time and date be captured automatically in the program? @ivyodametey and @IMQUARTEY can we try our hands on the functions within the datetime module?

**Comment by IMQUARTEY** [comment]
Sure

**Comment by Jeffreylarbiakor** [comment]
Please check out the version 2.0.0 released in the v.2.0.0 branch.
